#!/usr/bin/env bash
# Regenerates the landing page's copy of app-shared CSS/JS. Same pattern as
# src-tauri/prepare-web.sh's Tauri build: a canonical source lives once in
# the main tree, and a small script copies the exact slice a second deploy
# target needs, rather than hand-pasting it and letting it drift (which is
# exactly what happened before this script existed — see CLAUDE.md's PWA
# section and CHANGELOG.md v2.99 for the drift this replaced).
#
# Runs from the REPO ROOT — set as the landing Cloudflare Pages project's
# Build command (`bash landing/prepare-shared.sh`), same convention as
# prepare-web.sh being invoked from repo root by Tauri's beforeBuildCommand.
# Safe to re-run any time; both outputs are fully overwritten, never
# hand-edited in place — see the "AUTO-GENERATED" header this script writes
# into app-tokens.css, and the equivalent comment atop chart-math.js itself.
set -euo pipefail

# 1. Pure chart-math functions — single source is js/chart-math.js, copied
# verbatim. (landing/script.js's own call sites still supply their own
# colour constants as arguments — see its file header — only the threshold
# maths itself is shared.)
cp js/chart-math.js landing/chart-math.js

# 2. Design tokens — the :root block IS the shared surface; the ~5000
# surrounding lines of component CSS in css/styles.css aren't needed on a
# page with its own distinct layout, so only the :root slice is extracted,
# not the whole file. Relies on :root containing no nested braces (true
# today — CSS custom properties don't nest; re-verify this assumption if
# the extraction ever comes up short, rather than assuming a value is
# simply missing).
{
  echo '/* AUTO-GENERATED by landing/prepare-shared.sh — do NOT hand-edit.'
  echo "   Source of truth is css/styles.css's own :root block. Re-run this"
  echo "   script (or push — Cloudflare's Build command re-runs it) after"
  echo '   any token change there. */'
  awk '/^  :root \{/{f=1} f{print} f && /^  \}/{exit}' css/styles.css
} > landing/app-tokens.css
